### ISSUE TITLE
If last link is not in menu - no url displayed

### ISSUE THREAD

**Issue by Monschder** [krizalys/joomla-breadcrumbs#1]
Hi.
If the last link in the breadcrump is not in the menu there is no link. I've patched the default_microdata.php like that:

`if ($linkLast)
        {
            if ($item->link !=""){
                echo '<a href="' . $item->link . '" itemprop="url" class="pathway"><span itemprop="title">' . $item->name . '</span></a>';
            } else {
                echo '<a href="' . JURI::current() . '" itemprop="url" class="pathway"><span itemprop="title">' . $item->name . '</span></a>';
                }
        }
`

**Comment by krizalys** [comment]
Thanks for the report!
I'll look into this issue over the week end.
