### ISSUE TITLE
Changing http in https to be ssl compliant

### ISSUE THREAD

**Issue by charlynancy54** [krizalys/joomla-breadcrumbs#2]
Hi,
In this file : 
/modules/mod_krizalys_breadcrumbs/renderer/MicrodataBreadcrumbsRenderer.php
you have 2 times http that can be changed by https  without problem 
here are the part of code with https 
`    protected function getContainerAttrs()
    {
        return $this->makeItemScope()
            . ' itemtype="https://schema.org/BreadcrumbList"';
    }`
`    protected function getItemContainerAttrs()
    {
        return $this->makeItemScope() . ' itemprop="itemListElement"'
            . ' itemtype="https://schema.org/ListItem"';
    }`

**Comment by krizalys** [comment]
Hi, thanks for the suggestion.

In their official documentation, schema.org use only non-SSL URL for `itemtype` attributes. In fact, on the SSL-enabled https://schema.org/BreadcrumbList for example, we can see that the non SSL-enabled http://schema.org/BreadcrumbList is still the canonical URL for this schema. As I understand it, these URLs act more like namespaces than anchors, therefore it probably does not really matter whether they actually work or not.

Also, if the browser was actually expected to fetch them, this change would be useful only for SSL sites. For others, it would just add CPU overhead for the minor benefit of transferring a public schema securely.

Perhaps these changes require more thinking. At least, this should be configurable, and/or dependent on the site SSL flag. Also, it should be confirmed that microdata elements using these URLs still validate. If you have the time to investigate, please feel free to go ahead and open a PR.

Thanks.

**Comment by charlynancy54** [comment]
Hi,
i searched about this matter in other forums.
I saw a lot of discussions about that.
It seems, actually , that the tendency is to implement https everywhere.
The last Question on the FAQs of Schema;org is : 

> Q: Should we write 'https://schema.org' or 'http://schema.org' in our markup?
> There is a general trend towards using 'https' more widely, and you can already write 'https://schema.org' in your structured data. Over time we will migrate the schema.org site itself towards using https: as the default version of the site and our preferred form in examples. However 'http://schema.org' -based URLs in structured data markup will remain widely understood for the forseeable future and there should be no urgency about migrating existing data. This is a lengthy way of saying that both 'https://schema.org' and 'http://schema.org' are fine.

The validation seems to be OK. So i believe that you can implement now, everywhere, the HTTPS URLs.
It seems that non HTTPS sites have no problem with that.
So, no need to implement such things as : case 1 with HTTP, case 2 with HTTPS
