### ISSUE TITLE
In micro data , error in position field

### ISSUE THREAD

**Issue by charlynancy54** [krizalys/joomla-breadcrumbs#3]
in everry  microdata field "position" the same error :
position | A value for the position field is required.
here is the bad code :   `<meta property="position" content="2" />`
here is the goog code : `<meta itemprop="position" content="2" />`

To fix that , i change the file /renderer/BaseBreadcrumbsRenderer.php
Line 80 bad code : `$tag = '<meta property="position" content="' . $index . '"';`
Line 80 code fixed : `$tag = '<meta itemprop="position" content="' . $index . '"';`

**Comment by krizalys** [comment]
Thanks for reporting this @charlynancy54.
This is fixed in 1.1.1, let me know if it does not fix it for you.
