### ISSUE TITLE
Error when Show Last is on and Link Last is off

### ISSUE THREAD

**Issue by lllopo** [krizalys/joomla-breadcrumbs#8]
When Show Last is on and Link Last is off, [Google Structured Data Testing tool](https://search.google.com/structured-data/testing-tool) fails with error on last element : **The value provided for id must be a valid URL**.

**Comment by lllopo** [comment]
This is the solution :

```
<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
    <span itemscope itemtype="http://schema.org/Thing" itemprop="item" itemid="/category/this-page">
      <span itemprop="name">This page</span>
    </span>
    <meta itemprop="position" content="3" />
  </li>
```

Notice the **itemtype=thing** and **itemid** properties on the span

**Comment by krizalys** [comment]
@lllopo Thanks for sharing this! I was indeed looking for a solution to fix this.

Once you have tested it, please consider opening a pull request with this change. Otherwise, I'll try to test your proposed solution myself and include it this week-end.

**Comment by lllopo** [comment]
I've made a quick test in the google test tool and it solved it indeed. No time to do code changes and test, though.

**Comment by krizalys** [comment]
Thanks @Illopo I tested it and incorporated into the latest master. Will release an update shortly.

This also fixed https://github.com/krizalys/joomla-breadcrumbs/issues/7
